BUILD_UP_VALUE = 1
NO_DATA_VALUE = 0
RADIUS_VALUE = 2000

GROUP_NAME = "USM-Toolset"
GROUP_ID = "usm"

NAME_FIELD = "NAME_FIELD"
EMPLOYEE_FIELD = "EMPLOYEE_FIELD"
INHABITANT_FIELD = "INHABITANT_FIELD"
SSA_FIELD = "SSA_FIELD"
DIS_FIELD = "DIS_FIELD"
SETTLEMENT_AREA = "SETTLEMENT_AREA"

RASTER = "RASTER"
VECTOR = "VECTOR"

OUTPUT = "OUTPUT"
